language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.5"
env:
  - DB=sqlite
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/travis.database.yml config/database.yml
  - cp config/travis.papyrus_app_config.rb config/papyrus_app_config.rb
  - mysql -e 'create database papyrus_test'
