language: ruby
rvm:
  - "2.0.0"
  - "2.1.3"
env:
  - DB=sqlite
  - DB=mysql
bundler_args: --without development
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rake test:units
  - RAILS_ENV=test bundle exec rake test:functionals
before_script:
  - cp config/travis.database.yml config/database.yml
  - mysql -e 'create database papyrus_test'
